name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Robot Framework and dependencies
        run: |
          pip install robotframework
          pip install -r requirements.txt

      - name: Install Chrome and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y xvfb

      - name: Run Robot tests
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' \
          robot --variable HEADLESS:True -d log -i REGRESSIVO ./features
