name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install browser drivers and run tests
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        export PATH=$PATH:/usr/lib/chromium-browser/
        robot -d results features/

    - name: Upload Robot Framework reports
      uses: actions/upload-artifact@v2
      with:
        name: robot-report
        path: results/
